name: loud_cast
description: "A Neo-Brutalist style weather application built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  lottie: ^3.3.1
  font_awesome_flutter: ^10.9.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.5.0
  connectivity_plus: ^6.1.5
  intl: ^0.20.2
  url_launcher: ^6.3.2
  android_intent_plus: ^5.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # flutter_launcher_icons has been removed

flutter:
  uses-material-design: true

  assets:
    # Location for Lottie animation JSON files.
    - lib/assets/animations/
    # The assets/icon/ line has been removed

# The entire flutter_launcher_icons configuration block at the end is gone.